source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'ScrollView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

      pod 'MJRefresh'
      pod 'Masonry'
  # Pods for ScrollView

  target 'ScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScrollViewUITests' do
    # Pods for testing
  end

end
